### PR TITLE
fix gpg error in arch podman containers

### PR DESCRIPTION
**Pull request by kylon**
try to fallback to pinentry-mode loopback before giving up on error if ioctl error is present

### CODE REVIEW

**Comment by BrenekH** [comment]
Thanks for the PR!

I'm assuming that in order to test this I need to run the server in a non-interactive environment (like TTY) with a secured GPG key, correct?

**Comment by kylon** [comment]
i'm running a pod container from official arch image, interactive, using a key generated following the wiki (https://github.com/BrenekH/blinky/wiki/Signing-the-Database#creating-a-signing-key) specs, keys are secured by default if you create them

**Comment by BrenekH** [comment]
Sorry about the wait, but this looks good to me. Certainly not a final solution to fully supporting keys with passwords, but a good stop gap for those who do want to use them.

> btw, noticed now, that db is not singed even if key has been read

What do you mean by this? How are you checking if the database is signed?

**Comment by kylon** [comment]
there is no sig file for the db

**Comment by BrenekH** [comment]
So the problem is that `repo-add` is calling `gpg`, but the key is locked again. I don't know if there's a way to permanently unlock a GPG key

**Pull request merged**
